# Generated by Django 3.2.5 on 2021-07-29 09:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=20)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('toppings', multiselectfield.db.fields.MultiSelectField(choices=[('Corn', 'Corn'), ('Onions', 'Onions'), ('Jalapenos', 'Jalapenos'), ('Tomato', 'Tomato'), ('Bellpepper', 'Bellpepper'), ('Olives', 'Olives'), ('Extra Cheese', 'Cheese')], max_length=59)),
            ],
        ),
    ]
