# Generated by Django 3.2.5 on 2021-07-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizzamodel',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='topping',
            field=models.ManyToManyField(blank=True, to='preference.Toppings'),
        ),
    ]
