# Generated by Django 3.2.5 on 2021-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_auto_20210730_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='topping',
            field=models.CharField(choices=[('Corn', 'Corn'), ('Onions', 'Onions'), ('Jalapenos', 'Jalapenos'), ('Tomato', 'Tomato'), ('Bellpepper', 'Bellpepper'), ('Olives', 'Olives'), ('Extra Cheese', 'Cheese')], max_length=64, unique=True),
        ),
    ]
